In [3]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Importing the dataset
train = pd.read_csv("train_ready_for_model_loan.csv")
train.head()

Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0  LP001002             5849                0.0       126.0             360.0   
1  LP001003             4583             1508.0       128.0             360.0   
2  LP001005             3000                0.0        66.0             360.0   
3  LP001006             2583             2358.0       120.0             360.0   
4  LP001008             6000                0.0       141.0             360.0   

   Credit_History  Loan_Status  Gender_Female  Gender_Male  Married_No  \
0             1.0            1              0            1           1   
1             1.0            0              0            1           0   
2             1.0            1              0            1           0   
3             1.0            1              0            1           0   
4             1.0            1              0            1           1   

          ...           Dependents_1  Dependents_2  Dependents_3+  \
0         ...                      0             0              0   
1         ...                      1             0              0   
2         ...                      0             0              0   
3         ...                      0             0              0   
4         ...                      0             0              0   

   Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                   1                       0                 1   
1                   1                       0                 1   
2                   1                       0                 0   
3                   0                       1                 1   
4                   1                       0                 1   

   Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                  0                    0                        0   
1                  0                    1                        0   
2                  1                    0                        0   
3                  0                    0                        0   
4                  0                    0                        0   

   Property_Area_Urban  
0                    1  
1                    0  
2                    1  
3                    1  
4                    1  

[5 rows x 22 columns]

In [4]:
train.shape

(614, 22)

In [5]:
X=train.drop(columns=['Loan_Status','Loan_ID']).values
y = train.iloc[:,6].values
print(X)
print(y)

[[5.849e+03 0.000e+00 1.260e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [4.583e+03 1.508e+03 1.280e+02 ... 1.000e+00 0.000e+00 0.000e+00]
 [3.000e+03 0.000e+00 6.600e+01 ... 0.000e+00 0.000e+00 1.000e+00]
 ...
 [8.072e+03 2.400e+02 2.530e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [7.583e+03 0.000e+00 1.870e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [4.583e+03 0.000e+00 1.330e+02 ... 0.000e+00 1.000e+00 0.000e+00]]
[1 0 1 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0 1 0
 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0
 1 0 0 0 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 0 0 1 0 0 0 1 1 1 1 1 1 1
 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 1 0 1 0 0 0 1 0 1
 1 0 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 1 0 1 0 1
 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 0 1 1 1 0 1 1 1 1 0 0 1 1 0 1 0 0 0
 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 1 1 0 

In [22]:
test = pd.read_csv("test_ready_for_model_loan.csv")
test.head()

Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0  LP001015             5720                0.0       110.0             360.0   
1  LP001022             3076             1500.0       126.0             360.0   
2  LP001031             5000             1800.0       208.0             360.0   
3  LP001035             2340             2546.0       100.0             360.0   
4  LP001051             3276                0.0        78.0             360.0   

   Credit_History  Gender_Female  Gender_Male  Married_No  Married_Yes  \
0             1.0              0            1           0            1   
1             1.0              0            1           0            1   
2             1.0              0            1           0            1   
3             1.0              0            1           0            1   
4             1.0              0            1           1            0   

          ...           Dependents_1  Dependents_2  Dependents_3+  \
0         ...                      0             0              0   
1         ...                      1             0              0   
2         ...                      0             1              0   
3         ...                      0             1              0   
4         ...                      0             0              0   

   Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                   1                       0                 1   
1                   1                       0                 1   
2                   1                       0                 1   
3                   1                       0                 1   
4                   0                       1                 1   

   Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                  0                    0                        0   
1                  0                    0                        0   
2                  0                    0                        0   
3                  0                    0                        0   
4                  0                    0                        0   

   Property_Area_Urban  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1  

[5 rows x 21 columns]

In [26]:
X_test=test.drop(columns=['Loan_ID']).values
print(X_test)

[[5.720e+03 0.000e+00 1.100e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [3.076e+03 1.500e+03 1.260e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 [5.000e+03 1.800e+03 2.080e+02 ... 0.000e+00 0.000e+00 1.000e+00]
 ...
 [3.250e+03 1.993e+03 1.260e+02 ... 0.000e+00 1.000e+00 0.000e+00]
 [5.000e+03 2.393e+03 1.580e+02 ... 1.000e+00 0.000e+00 0.000e+00]
 [9.200e+03 0.000e+00 9.800e+01 ... 1.000e+00 0.000e+00 0.000e+00]]


In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [27]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X=sc.fit_transform(X)
X_test=sc.transform(X_test)

In [28]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [29]:
classifier=Sequential()

In [60]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim=20,init='uniform',activation='relu',input_dim=20))
classifier.add(Dropout(0.6))
# Adding second hidden layer
classifier.add(Dense(output_dim=60,init='uniform',activation='relu'))
classifier.add(Dropout(0.6))
classifier.add(Dense(output_dim=30,init='uniform',activation='relu'))
classifier.add(Dropout(0.6))

classifier.add(Dense(output_dim=80,init='uniform',activation='relu'))
classifier.add(Dropout(0.6))

classifier.add(Dense(output_dim=60,init='uniform',activation='relu'))
classifier.add(Dropout(0.6))

#Adding the output layer
classifier.add(Dense(output_dim=1,init='uniform',activation='sigmoid'))

C:\Users\SHALINI\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=20, units=20, kernel_initializer="uniform")`
  
C:\Users\SHALINI\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=60, kernel_initializer="uniform")`
  """
C:\Users\SHALINI\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=30, kernel_initializer="uniform")`
  import sys
C:\Users\SHALINI\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=80, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
C:\Users\SHALINI\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: 

In [74]:
classifier.add?

In [61]:
#Compiling nueral network
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [62]:
print(X.shape)
print(X_test.shape)
print(y.shape)
#print(y_test.shape)

(614, 20)
(367, 20)
(614,)


In [63]:
classifier.fit(X,y,batch_size=10,nb_epoch=100)

C:\Users\SHALINI\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/1000
614/614 [==============================] - 1s 2ms/step - loss: 0.6923 - acc: 0.6417
Epoch 2/1000
614/614 [==============================] - 0s 261us/step - loss: 0.6895 - acc: 0.6873
Epoch 3/1000
614/614 [==============================] - 0s 254us/step - loss: 0.6857 - acc: 0.6873
Epoch 4/1000
614/614 [==============================] - 0s 259us/step - loss: 0.6803 - acc: 0.6873
Epoch 5/1000
614/614 [==============================] - 0s 264us/step - loss: 0.6707 - acc: 0.6873
Epoch 6/1000
614/614 [==============================] - 0s 261us/step - loss: 0.6547 - acc: 0.6873
Epoch 7/1000
614/614 [==============================] - 0s 249us/step - loss: 0.6295 - acc: 0.6873
Epoch 8/1000
614/614 [==============================] - 0s 265us/step - loss: 0.6000 - acc: 0.6873
Epoch 9/1000
614/614 [==============================] - 0s 256us/step - loss: 0.6057 - acc: 0.6873
Epoch 10/1000
614/614 [==============================] - 0s 249us/step - loss: 0.5825 - acc: 0.6873
Epoch 11/10

614/614 [==============================] - 0s 256us/step - loss: 0.3108 - acc: 0.9072
Epoch 84/1000
614/614 [==============================] - 0s 252us/step - loss: 0.3302 - acc: 0.8779
Epoch 85/1000
614/614 [==============================] - 0s 275us/step - loss: 0.2955 - acc: 0.8941
Epoch 86/1000
614/614 [==============================] - 0s 248us/step - loss: 0.2919 - acc: 0.9023
Epoch 87/1000
614/614 [==============================] - 0s 241us/step - loss: 0.3080 - acc: 0.8827
Epoch 88/1000
614/614 [==============================] - 0s 265us/step - loss: 0.2795 - acc: 0.9104
Epoch 89/1000
614/614 [==============================] - 0s 249us/step - loss: 0.2430 - acc: 0.9283
Epoch 90/1000
614/614 [==============================] - 0s 243us/step - loss: 0.2656 - acc: 0.9218
Epoch 91/1000
614/614 [==============================] - 0s 252us/step - loss: 0.2645 - acc: 0.9283
Epoch 92/1000
614/614 [==============================] - 0s 254us/step - loss: 0.3244 - acc: 0.9039
Epoch 93/1000


614/614 [==============================] - 0s 249us/step - loss: 0.2490 - acc: 0.9202
Epoch 165/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2693 - acc: 0.9153
Epoch 166/1000
614/614 [==============================] - 0s 228us/step - loss: 0.2662 - acc: 0.9186
Epoch 167/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2686 - acc: 0.9169
Epoch 168/1000
614/614 [==============================] - 0s 226us/step - loss: 0.2630 - acc: 0.9088
Epoch 169/1000
614/614 [==============================] - 0s 236us/step - loss: 0.2698 - acc: 0.9153
Epoch 170/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2738 - acc: 0.9121
Epoch 171/1000
614/614 [==============================] - 0s 226us/step - loss: 0.2738 - acc: 0.9153
Epoch 172/1000
614/614 [==============================] - 0s 236us/step - loss: 0.2493 - acc: 0.9283
Epoch 173/1000
614/614 [==============================] - 0s 226us/step - loss: 0.2840 - acc: 0.8974
Epoch

614/614 [==============================] - 0s 241us/step - loss: 0.2532 - acc: 0.9055
Epoch 245/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2360 - acc: 0.9235
Epoch 246/1000
614/614 [==============================] - 0s 249us/step - loss: 0.2660 - acc: 0.9121
Epoch 247/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2184 - acc: 0.9186
Epoch 248/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2395 - acc: 0.9218
Epoch 249/1000
614/614 [==============================] - 0s 248us/step - loss: 0.2632 - acc: 0.9137
Epoch 250/1000
614/614 [==============================] - 0s 254us/step - loss: 0.2166 - acc: 0.9121
Epoch 251/1000
614/614 [==============================] - 0s 252us/step - loss: 0.2541 - acc: 0.9137
Epoch 252/1000
614/614 [==============================] - 0s 243us/step - loss: 0.2429 - acc: 0.9137
Epoch 253/1000
614/614 [==============================] - 0s 246us/step - loss: 0.2680 - acc: 0.9153
Epoch

614/614 [==============================] - 0s 246us/step - loss: 0.2326 - acc: 0.9072
Epoch 326/1000
614/614 [==============================] - 0s 243us/step - loss: 0.2337 - acc: 0.9349
Epoch 327/1000
614/614 [==============================] - 0s 238us/step - loss: 0.2166 - acc: 0.9235
Epoch 328/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2376 - acc: 0.9218
Epoch 329/1000
614/614 [==============================] - 0s 230us/step - loss: 0.2425 - acc: 0.9088
Epoch 330/1000
614/614 [==============================] - 0s 230us/step - loss: 0.1987 - acc: 0.9414
Epoch 331/1000
614/614 [==============================] - 0s 238us/step - loss: 0.2077 - acc: 0.9251
Epoch 332/1000
614/614 [==============================] - 0s 230us/step - loss: 0.2078 - acc: 0.9283
Epoch 333/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2693 - acc: 0.9121
Epoch 334/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2106 - acc: 0.9283
Epoch

614/614 [==============================] - 0s 285us/step - loss: 0.2144 - acc: 0.9186
Epoch 407/1000
614/614 [==============================] - 0s 265us/step - loss: 0.2601 - acc: 0.9137
Epoch 408/1000
614/614 [==============================] - 0s 241us/step - loss: 0.2589 - acc: 0.9153
Epoch 409/1000
614/614 [==============================] - 0s 236us/step - loss: 0.2218 - acc: 0.9251
Epoch 410/1000
614/614 [==============================] - 0s 230us/step - loss: 0.2221 - acc: 0.9235
Epoch 411/1000
614/614 [==============================] - 0s 230us/step - loss: 0.2497 - acc: 0.9283
Epoch 412/1000
614/614 [==============================] - 0s 246us/step - loss: 0.2446 - acc: 0.9153
Epoch 413/1000
614/614 [==============================] - 0s 230us/step - loss: 0.2261 - acc: 0.9397
Epoch 414/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2387 - acc: 0.9153
Epoch 415/1000
614/614 [==============================] - 0s 238us/step - loss: 0.2328 - acc: 0.9202
Epoch

614/614 [==============================] - 0s 262us/step - loss: 0.2535 - acc: 0.9137
Epoch 488/1000
614/614 [==============================] - 0s 239us/step - loss: 0.2639 - acc: 0.9186
Epoch 489/1000
614/614 [==============================] - 0s 244us/step - loss: 0.2236 - acc: 0.9283
Epoch 490/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2554 - acc: 0.9153
Epoch 491/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2154 - acc: 0.9121
Epoch 492/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2085 - acc: 0.9104
Epoch 493/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2178 - acc: 0.9365
Epoch 494/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2091 - acc: 0.9300
Epoch 495/1000
614/614 [==============================] - 0s 228us/step - loss: 0.2273 - acc: 0.9332
Epoch 496/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2407 - acc: 0.9332
Epoch

614/614 [==============================] - 0s 241us/step - loss: 0.2495 - acc: 0.9283
Epoch 569/1000
614/614 [==============================] - 0s 228us/step - loss: 0.2406 - acc: 0.9202
Epoch 570/1000
614/614 [==============================] - 0s 225us/step - loss: 0.2243 - acc: 0.9153
Epoch 571/1000
614/614 [==============================] - 0s 246us/step - loss: 0.2378 - acc: 0.9202
Epoch 572/1000
614/614 [==============================] - 0s 239us/step - loss: 0.2454 - acc: 0.9186
Epoch 573/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2163 - acc: 0.9267
Epoch 574/1000
614/614 [==============================] - 0s 225us/step - loss: 0.2317 - acc: 0.9397
Epoch 575/1000
614/614 [==============================] - 0s 225us/step - loss: 0.2385 - acc: 0.9235
Epoch 576/1000
614/614 [==============================] - 0s 223us/step - loss: 0.2092 - acc: 0.9267
Epoch 577/1000
614/614 [==============================] - 0s 228us/step - loss: 0.2879 - acc: 0.9121
Epoch

614/614 [==============================] - 0s 239us/step - loss: 0.2493 - acc: 0.9316
Epoch 650/1000
614/614 [==============================] - 0s 228us/step - loss: 0.2556 - acc: 0.9202
Epoch 651/1000
614/614 [==============================] - 0s 226us/step - loss: 0.2432 - acc: 0.9007
Epoch 652/1000
614/614 [==============================] - 0s 228us/step - loss: 0.2289 - acc: 0.9186
Epoch 653/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2287 - acc: 0.9137
Epoch 654/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2194 - acc: 0.9235
Epoch 655/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2005 - acc: 0.9235
Epoch 656/1000
614/614 [==============================] - 0s 236us/step - loss: 0.2141 - acc: 0.9267
Epoch 657/1000
614/614 [==============================] - 0s 223us/step - loss: 0.2309 - acc: 0.9316
Epoch 658/1000
614/614 [==============================] - 0s 257us/step - loss: 0.2272 - acc: 0.9235
Epoch

Epoch 730/1000
614/614 [==============================] - 0s 252us/step - loss: 0.2236 - acc: 0.9104
Epoch 731/1000
614/614 [==============================] - 0s 241us/step - loss: 0.2259 - acc: 0.9251
Epoch 732/1000
614/614 [==============================] - 0s 236us/step - loss: 0.1912 - acc: 0.9397
Epoch 733/1000
614/614 [==============================] - 0s 239us/step - loss: 0.1828 - acc: 0.9397
Epoch 734/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2366 - acc: 0.9267
Epoch 735/1000
614/614 [==============================] - 0s 238us/step - loss: 0.2339 - acc: 0.9316
Epoch 736/1000
614/614 [==============================] - 0s 236us/step - loss: 0.1969 - acc: 0.9300
Epoch 737/1000
614/614 [==============================] - 0s 231us/step - loss: 0.1951 - acc: 0.9283
Epoch 738/1000
614/614 [==============================] - 0s 249us/step - loss: 0.2284 - acc: 0.9300
Epoch 739/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2368 - ac

614/614 [==============================] - 0s 241us/step - loss: 0.1944 - acc: 0.9267
Epoch 812/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2067 - acc: 0.9169
Epoch 813/1000
614/614 [==============================] - 0s 239us/step - loss: 0.2250 - acc: 0.9397
Epoch 814/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2189 - acc: 0.9104
Epoch 815/1000
614/614 [==============================] - 0s 223us/step - loss: 0.2070 - acc: 0.9381
Epoch 816/1000
614/614 [==============================] - 0s 239us/step - loss: 0.2702 - acc: 0.9251
Epoch 817/1000
614/614 [==============================] - 0s 241us/step - loss: 0.2195 - acc: 0.9218
Epoch 818/1000
614/614 [==============================] - 0s 230us/step - loss: 0.1899 - acc: 0.9267
Epoch 819/1000
614/614 [==============================] - 0s 228us/step - loss: 0.2295 - acc: 0.9218
Epoch 820/1000
614/614 [==============================] - 0s 238us/step - loss: 0.1914 - acc: 0.9218
Epoch

614/614 [==============================] - 0s 241us/step - loss: 0.2092 - acc: 0.9316
Epoch 893/1000
614/614 [==============================] - 0s 226us/step - loss: 0.2249 - acc: 0.9381
Epoch 894/1000
614/614 [==============================] - 0s 236us/step - loss: 0.2067 - acc: 0.9267
Epoch 895/1000
614/614 [==============================] - 0s 231us/step - loss: 0.2369 - acc: 0.9169
Epoch 896/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2067 - acc: 0.9283
Epoch 897/1000
614/614 [==============================] - 0s 244us/step - loss: 0.2184 - acc: 0.9267
Epoch 898/1000
614/614 [==============================] - 0s 238us/step - loss: 0.1968 - acc: 0.9267
Epoch 899/1000
614/614 [==============================] - 0s 239us/step - loss: 0.2326 - acc: 0.9235
Epoch 900/1000
614/614 [==============================] - 0s 267us/step - loss: 0.2282 - acc: 0.9137
Epoch 901/1000
614/614 [==============================] - 0s 243us/step - loss: 0.2169 - acc: 0.9300
Epoch

614/614 [==============================] - 0s 244us/step - loss: 0.2359 - acc: 0.9235
Epoch 974/1000
614/614 [==============================] - 0s 235us/step - loss: 0.2159 - acc: 0.9332
Epoch 975/1000
614/614 [==============================] - 0s 236us/step - loss: 0.1958 - acc: 0.9349
Epoch 976/1000
614/614 [==============================] - 0s 238us/step - loss: 0.2088 - acc: 0.9283
Epoch 977/1000
614/614 [==============================] - 0s 233us/step - loss: 0.1807 - acc: 0.9316
Epoch 978/1000
614/614 [==============================] - 0s 230us/step - loss: 0.2507 - acc: 0.9137
Epoch 979/1000
614/614 [==============================] - 0s 233us/step - loss: 0.1860 - acc: 0.9479
Epoch 980/1000
614/614 [==============================] - 0s 233us/step - loss: 0.2212 - acc: 0.9332
Epoch 981/1000
614/614 [==============================] - 0s 226us/step - loss: 0.2779 - acc: 0.9169
Epoch 982/1000
614/614 [==============================] - 0s 244us/step - loss: 0.2625 - acc: 0.9088
Epoch

In [64]:
from sklearn.metrics import accuracy_score
y_pred=classifier.predict(X_train)
y_pred=(y_pred>0.5)
accuracy_score(y_pred,y_train)

0.9653767820773931

In [70]:
target = 'Loan_Status'
IDcol = ['Loan_ID']
#Predicting the test results
y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.7)
test[target]=y_pred

In [71]:
test

Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  \
0    LP001015             5720                0.0       110.0   
1    LP001022             3076             1500.0       126.0   
2    LP001031             5000             1800.0       208.0   
3    LP001035             2340             2546.0       100.0   
4    LP001051             3276                0.0        78.0   
5    LP001054             2165             3422.0       152.0   
6    LP001055             2226                0.0        59.0   
7    LP001056             3881                0.0       147.0   
8    LP001059            13633                0.0       280.0   
9    LP001067             2400             2400.0       123.0   
10   LP001078             3091                0.0        90.0   
11   LP001082             2185             1516.0       162.0   
12   LP001083             4166                0.0        40.0   
13   LP001094            12173                0.0       166.0   
14   LP001096             4666                0.0       124.0   
15   LP001099             5667                0.0       131.0   
16   LP001105             4583             2916.0       200.0   
17   LP001107             3786              333.0       126.0   
18   LP001108             9226             7916.0       300.0   
19   LP001115             1300             3470.0       100.0   
20   LP001121             1888             1620.0        48.0   
21   LP001124             2083                0.0        28.0   
22   LP001128             3909                0.0       101.0   
23   LP001135             3765                0.0       125.0   
24   LP001149             5400             4380.0       290.0   
25   LP001153                0            24000.0       148.0   
26   LP001163             4363             1250.0       140.0   
27   LP001169             7500             3750.0       275.0   
28   LP001174             3772              833.0        57.0   
29   LP001176             2942             2382.0       125.0   
..        ...              ...                ...         ...   
337  LP002856             2292             1558.0       119.0   
338  LP002857             2360             3355.0        87.0   
339  LP002858             4333             2333.0       162.0   
340  LP002860             2623             4831.0       122.0   
341  LP002867             3972             4275.0       187.0   
342  LP002869             3522                0.0        81.0   
343  LP002870             4700                0.0        80.0   
344  LP002876             6858                0.0       176.0   
345  LP002878             8334                0.0       260.0   
346  LP002879             3391             1966.0       133.0   
347  LP002885             2868                0.0        70.0   
348  LP002890             3418             1380.0       135.0   
349  LP002891             2500              296.0       137.0   
350  LP002899             8667                0.0       254.0   
351  LP002901             2283            15000.0       106.0   
352  LP002907             5817              910.0       109.0   
353  LP002920             5119             3769.0       120.0   
354  LP002921             5316              187.0       158.0   
355  LP002932             7603             1213.0       197.0   
356  LP002935             3791             1936.0        85.0   
357  LP002952             2500                0.0        60.0   
358  LP002954             3132                0.0        76.0   
359  LP002962             4000             2667.0       152.0   
360  LP002965             8550             4255.0        96.0   
361  LP002969             2269             2167.0        99.0   
362  LP002971             4009             1777.0       113.0   
363  LP002975             4158              709.0       115.0   
364  LP002980             3250             1993.0       126.0   
365  LP002986             5000             2393.0       158.0   
366  LP002989             9200           

In [72]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

ValueError: Found input variables with inconsistent numbers of samples: [123, 367]

In [73]:
IDcol.append(target)
submission=pd.DataFrame({x:test[x] for x in IDcol})
submission['Loan_Status']=submission.Loan_Status.replace({True:'Y',False:'N'})
submission.to_csv('res_dl_1.csv',index=False)
submission

Loan_ID Loan_Status
0    LP001015           Y
1    LP001022           Y
2    LP001031           Y
3    LP001035           Y
4    LP001051           Y
5    LP001054           Y
6    LP001055           Y
7    LP001056           Y
8    LP001059           Y
9    LP001067           Y
10   LP001078           Y
11   LP001082           Y
12   LP001083           Y
13   LP001094           Y
14   LP001096           Y
15   LP001099           Y
16   LP001105           Y
17   LP001107           Y
18   LP001108           Y
19   LP001115           Y
20   LP001121           Y
21   LP001124           Y
22   LP001128           Y
23   LP001135           Y
24   LP001149           Y
25   LP001153           N
26   LP001163           Y
27   LP001169           Y
28   LP001174           Y
29   LP001176           Y
..        ...         ...
337  LP002856           Y
338  LP002857           Y
339  LP002858           Y
340  LP002860           Y
341  LP002867           Y
342  LP002869           Y
343  LP002870           Y
344  LP002876           Y
345  LP002878           Y
346  LP002879           Y
347  LP002885           Y
348  LP002890           Y
349  LP002891           Y
350  LP002899           Y
351  LP002901           N
352  LP002907           Y
353  LP002920           Y
354  LP002921           Y
355  LP002932           Y
356  LP002935           Y
357  LP002952           Y
358  LP002954           Y
359  LP002962           Y
360  LP002965           Y
361  LP002969           Y
362  LP002971           Y
363  LP002975           Y
364  LP002980           Y
365  LP002986           Y
366  LP002989           Y

[367 rows x 2 columns]